# Generated by Django 3.2.25 on 2024-03-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaCart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsorders',
            old_name='product_id',
            new_name='product_sku',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InstaCart.usertype'),
        ),
        migrations.AlterUniqueTogether(
            name='productsorders',
            unique_together={('order_id', 'product_sku')},
        ),
    ]
